<?php
declare(strict_types=1);

require_once 'vendor/autoload.php';

use PHPUnit\Framework\TestCase;

final class CircleTest extends TestCase
{
  /**
   * @var ShapeInterface $shape Shape
   * @var float $ratio Ratio
   */
  private $shape;
  private $ratio;

  /**
   * Setting up the test
   */
  public function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub
    $scale=14;
    $this->ratio = 2.1234567890123;
    $radius = 3.123;
    //Instantiating a shape object
    $this->shape = new Shapes\Circle($radius, $scale);
  }

  /**
   * Testing ::getArea()
   * @throws Exception
   */
  public function testGetArea(): void
  {
    $actual = $this->shape->getArea();
    $this->assertEquals(30.64035841591363, $actual);
  }

  /**
   * Testing ::getPerimeter()
   * @throws Exception
   */
  public function testGetPerimeter(): void
  {
    $actual = $this->shape->getPerimeter();
    $this->assertEquals(19.62238771432189, $actual);
  }

  /**
   * Testing ::resize(float $ratio)
   * @throws Exception
   */
  public function testResize(): void
  {
    $this->shape->resize($this->ratio);
    $actualArea = $this->shape->getArea();
    $actualPerimeter = $this->shape->getPerimeter();
    $this->assertEquals(138.15948215634, $actualArea);
    $this->assertEquals(41.667292408608, $actualPerimeter);
  }

}